language: objective-c
os: osx
osx_image: xcode9.2


before_install:
  - gem install cocoapods
  - brew update

script:
  - xcodebuild -project StarDraw/StarDraw.xcodeproj -scheme StarDraw -sdk iphonesimulator -destination 'platform=iOS,id=iPhoneUUID' -configuration Debug build test
  - xcodebuild -project DesenhoView/DesenhoView.xcodeproj -scheme DesenhoView -sdk iphonesimulator -destination 'platform=iOS,id=iPhoneUUID' -configuration Debug build test
  - xcodebuild -project BugDraw/BugDraw.xcodeproj -scheme BugDraw -sdk iphonesimulator -destination 'platform=iOS,id=iPhoneUUID' -configuration Debug build test
